version: '3.9'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Your Password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: Username
      MYSQL_PASSWORD: Your Password
    volumes:
      -  ./mysql:/var/lib/mysql
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8020:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: Your
      WORDPRESS_DB_PASSWORD: Your
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

volumes:
  mysql_data: {}
